---
kind: pipeline
name: php-7.3

platform:
  os: linux
  arch: amd64

clone:
  depth: 0
  tags: true

steps:
- name: setup docker
  pull: always
  image: quay.io/presslabs/bfc
  environment: &baseEnv
    PHP_VERSION: 7.3.7
    WORDPRESS_VERSION: 5.2.2
    TAG_SUFFIX: ${DRONE_BRANCH/master/}
  commands:
    - dockerize -wait unix:///var/run/docker.sock -timeout 10s
    - docker info
    - make pull-cache
    - docker pull percona:5.7
  volumes:
  - name: dockersock
    path: /var/run

- name: build
  image: quay.io/presslabs/bfc
  depends_on: [setup docker]
  environment: &baseEnv
    PHP_VERSION: 7.3.7
    TAG_SUFFIX: ${DRONE_BRANCH/master/}
  commands:
    - make images
  volumes:
  - name: dockersock
    path: /var/run

- name: test php image
  image: quay.io/presslabs/bfc
  depends_on: [build]
  environment:
    <<: *baseEnv
  commands:
    - make .build/test/php
  volumes:
  - name: dockersock
    path: /var/run

- name: test wordpress image
  image: quay.io/presslabs/bfc
  depends_on: [build]
  environment:
    <<: *baseEnv
    TEST_HOSTNAME: docker
  commands:
    - make .build/test/wordpress
  volumes:
  - name: dockersock
    path: /var/run

- name: test bedrock image
  image: quay.io/presslabs/bfc
  depends_on: [build]
  environment:
    <<: *baseEnv
    TEST_HOSTNAME: docker
  commands:
    - make .build/test/bedrock
  volumes:
  - name: dockersock
    path: /var/run

- name: publish
  depends_on:
    - test php image
    - test wordpress image
    - test bedrock image
  image: quay.io/presslabs/bfc
  environment:
    <<: *baseEnv
    DOCKER_USER: "presslabs+drone"
    DOCKER_PASSWORD:
      from_secret: QUAY_TOKEN
  commands:
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD" quay.io
    - make push-images
  volumes:
  - name: dockersock
    path: /var/run

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
