templates:
  publish-wordpress: &publish-wordpress
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/wordpress-runtime
    context: wordpress
    dockerfile: wordpress/Dockerfile
    squash: true
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD

pipeline:
  publish-php-runtime-image:
    image: plugins/docker
    context: php
    dockerfile: php/Dockerfile
    registry: quay.io
    repo: quay.io/presslabs/php-runtime
    username: presslabs+drone
    tags: ["${PHP_SERIES}-latest", "${PHP_VERSION}", "${PHP_VERSION}-r${DRONE_BUILD_NUMBER}"]
    cache_from: ["quay.io/presslabs/php-runtime:${PHP_SERIES}-${DRONE_BRANCH/master/latest}"]
    build_args:
      - PHP_VERSION=${PHP_VERSION}
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: push
      branch: master

  publish-worpress-runtime-image:
    <<: *publish-wordpress
    target: classic
    tags:
      - ${WORDPRESS_VERSION}
      - ${WORDPRESS_VERSION}-php${PHP_SERIES}
      - ${WORDPRESS_VERSION}-php${PHP_SERIES}-r${DRONE_BUILD_NUMBER}
      - ${WORDPRESS_VERSION}-php${PHP_VERSION}
      - ${WORDPRESS_VERSION}-php${PHP_VERSION}-r${DRONE_BUILD_NUMBER}
    build_args:
      - BASE_IMAGE=quay.io/presslabs/php-runtime:${PHP_VERSION}-r${DRONE_BUILD_NUMBER}
      - WP_VERSION=${WORDPRESS_VERSION}
    when:
      event: push
      branch: master

  publish-bedrock-runtime-image:
    <<: *publish-wordpress
    group: publish-bedrock
    target: bedrock
    tags:
      - bedrock
      - bedrock-php${PHP_SERIES}
      - bedrock-php${PHP_SERIES}-r${DRONE_BUILD_NUMBER}
      - bedrock-php${PHP_VERSION}
      - bedrock-php${PHP_VERSION}-r${DRONE_BUILD_NUMBER}
    build_args:
      - BASE_IMAGE=quay.io/presslabs/php-runtime:${PHP_VERSION}-r${DRONE_BUILD_NUMBER}
    cache_from:
      - ${WORDPRESS_VERSION}-php${PHP_VERSION}-r${DRONE_BUILD_NUMBER}
    when:
      event: push
      branch: master

  publish-bedrock-builder-image:
    <<: *publish-wordpress
    target: bedrock-build
    group: publish-bedrock
    tags:
      - bedrock-build
      - bedrock-build-php${PHP_SERIES}
      - bedrock-build-php${PHP_SERIES}-r${DRONE_BUILD_NUMBER}
      - bedrock-build-php${PHP_VERSION}
      - bedrock-build-php${PHP_VERSION}-r${DRONE_BUILD_NUMBER}
    build_args:
      - BASE_IMAGE=quay.io/presslabs/php-runtime:${PHP_VERSION}-r${DRONE_BUILD_NUMBER}
    cache_from:
      - ${WORDPRESS_VERSION}-php${PHP_VERSION}-r${DRONE_BUILD_NUMBER}
    when:
      event: push
      branch: master

matrix:
  include:
    - PHP_SERIES: "7.3"
      PHP_VERSION: "7.3.6"
      WORDPRESS_VERSION: "5.2.2"
